In [1]:
import numpy as np

In [2]:
a= np.array([[1,3,5,6,7,8], [8,9,4,6,2,1], [4,7,9,3,1,0]])

In [3]:
print("a.shape: ", a.shape)
print("np.shape(a): ", np.shape(a))
print("a.size: ", a.size)
print("np.size(a): ", np.size(a))

a.shape:  (3, 6)
np.shape(a):  (3, 6)
a.size:  18
np.size(a):  18


In [10]:
# np.arange()       return fixed step array
print("np.arange(3):", np.arange(3))
print("np.arange(3,8):", np.arange(3,8))             #assign start and end points
print("np.arange(3,8,0.5):", np.arange(3,8,0.5))     #assign the step, 0.5

np.arange(3): [0 1 2]
np.arange(3,8): [3 4 5 6 7]
np.arange(3,8,0.5): [3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]


In [11]:
# np.asarray
a= [(1,2,3), (4,5,6)]
print("before np.asarray:", a)
a= np.asarray(a)
print("after np.asarray:", a)

before np.asarray: [(1, 2, 3), (4, 5, 6)]
after np.asarray: [[1 2 3]
 [4 5 6]]


In [3]:
# slice operation
print("a[0]:", a[0])                # elements in a row
# print("a(0):", a(0)) -> error
print("a[:,0]:", a[:,0])            # elements in a column
print("a[0,0]:", a[0,0])            # return element based on row and column index
print("a[-1,:]:", a[-1,:])          # elements in last row
print("a[:,-1]:", a[:,-1])          # elements in last column
print("a[-1]:", a[-1])              # elements in last row
print("a[:-1]:", a[:-1])            # elements in first two rows, minus 1 row
print("a[:-2]:", a[:-2])            # elements in first row, minus 2 rows
print("a[-1:]:", a[-1:])            # elements in last row
print("a[-2:]:", a[-2:])

a[0]: [1 3 5 6 7 8]


TypeError: 'numpy.ndarray' object is not callable

In [45]:
a= np.array([[1,3], [8,9]])
b= np.array([[1, 8], [3, 9], [5, 4], [6, 6], [7, 2], [8,1]])

# axis=0, [[y(i)- x(i)]]
print(np.diff(b, axis=0))
# axis=1, [[x(i+1)- x(i)], [y(i+1)-y(i)]]
# print(np.diff(b, axis=1))

print(np.sum(np.power(np.diff(b, axis=0),2),axis=1))

[[ 2  1]
 [ 2 -5]
 [ 1  2]
 [ 1 -4]
 [ 1 -1]]
[ 5 29  5 17  2]


In [ ]:
print(np.shape(b))
c=np.vstack((b[-1:], b, b[:-1]))
print(c)
print(c[1:,0])
print(c[:-1,0])

In [35]:
s= np.array([1,2,3,4,5,6,7,8,9])
print(s[1:])
print(s[:-1])

[2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]
